### ISSUE TITLE
Quick pointer to fellow Rust AoC implementation

### ISSUE THREAD

**Issue by nakedible** [jkaye2012/aoc2023#1]
Hi,

Read your article on AoC with Rust, and thought I'd just drop a link to my own solutions:

https://github.com/nakedible/aoc-2023-rs

It's not optimized for time specifically, especially not on the testing front, but all days all solutions takes <1.5 sec on my test machine.

Thought you might be interested in taking a peek.

**Comment by jkaye2012** [comment]
Thanks for sharing!
